// AUTO-GENERATED by scripts/inject-env.js — DO NOT EDIT
/* eslint-disable */
import { readFileSync } from "fs";
import { join } from "path";

// Build-time injected values (overwritten by prebuild script)
export const GOOGLE_CLIENT_ID = "";
export const GOOGLE_CLIENT_SECRET = "";
export const GOOGLE_REDIRECT_URI = "";
export const OAUTH_ENCRYPTION_KEY = "";
export const CRON_SECRET = "";
export const BLOG_API_KEY = "";

// Runtime fallback: read from JSON file if TS exports are empty
let _cache: Record<string, string> | null = null;

function loadFromJson(): Record<string, string> {
  if (_cache) return _cache;
  try {
    // Try multiple possible paths for the JSON file
    const paths = [
      join(process.cwd(), "env-injected.json"),
      join(__dirname, "..", "..", "env-injected.json"),
      join(__dirname, "..", "..", "..", "env-injected.json"),
      "/var/task/env-injected.json",
    ];
    for (const p of paths) {
      try {
        const raw = readFileSync(p, "utf8");
        _cache = JSON.parse(raw);
        return _cache!;
      } catch {
        continue;
      }
    }
  } catch {
    // ignore
  }
  _cache = {};
  return _cache;
}

export function getEnv(key: string): string {
  // 1. Check process.env first
  if (process.env[key]) return process.env[key]!;
  // 2. Check JSON fallback
  const json = loadFromJson();
  return json[key] || "";
}
