/**
 * Environment variable access with build-time injection fallback.
 * Workaround for Vercel bug where newly added env vars are not
 * injected into serverless function runtime.
 *
 * env-values.ts is auto-generated by scripts/inject-env.js at build time
 * with the actual values baked in.
 */
import * as injected from "@/lib/env-values";

export function getEnv(key: string): string {
  // 1. Runtime process.env (works for vars added at project creation)
  if (process.env[key]) return process.env[key]!;
  // 2. Build-time injected values (workaround for newer vars)
  const val = (injected as Record<string, string>)[key];
  return val || "";
}
