// AUTO-GENERATED by scripts/inject-env.js — DO NOT EDIT
/* eslint-disable */

export const GOOGLE_CLIENT_ID = "";
export const GOOGLE_CLIENT_SECRET = "";
export const GOOGLE_REDIRECT_URI = "";
export const OAUTH_ENCRYPTION_KEY = "";
export const CRON_SECRET = "";
export const BLOG_API_KEY = "";
