// AUTO-GENERATED by scripts/inject-env.js at build time
// DO NOT EDIT — values are injected from Vercel env vars during build
// This placeholder is committed so TypeScript doesn't error before prebuild runs

export const GOOGLE_CLIENT_ID = "";
export const GOOGLE_CLIENT_SECRET = "";
export const GOOGLE_REDIRECT_URI = "";
export const OAUTH_ENCRYPTION_KEY = "";
export const CRON_SECRET = "";
export const BLOG_API_KEY = "";

// Helper to get all injected env vars as a record
export const injectedEnv: Record<string, string> = {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  OAUTH_ENCRYPTION_KEY,
  CRON_SECRET,
  BLOG_API_KEY,
};
