/**
 * Prebuild script: injects env vars into a generated TypeScript module.
 *
 * Workaround for Vercel bug where env vars added after initial project setup
 * are available during build but NOT injected into serverless function runtime.
 *
 * This script reads env vars from process.env (confirmed available at build time)
 * and writes them as hardcoded exports in src/lib/env-runtime.ts.
 * Next.js bundles this module into the serverless function, making the values
 * available at runtime regardless of Vercel's env injection.
 */
const fs = require("fs");
const path = require("path");

const ENV_KEYS = [
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GOOGLE_REDIRECT_URI",
  "OAUTH_ENCRYPTION_KEY",
  "CRON_SECRET",
  "BLOG_API_KEY",
];

const outputPath = path.join(__dirname, "..", "src", "lib", "env-runtime.ts");

const lines = [
  "// AUTO-GENERATED by scripts/inject-env.js at build time",
  "// DO NOT EDIT — values are injected from Vercel env vars during build",
  "",
];

let count = 0;
for (const key of ENV_KEYS) {
  const value = process.env[key] || "";
  lines.push(`export const ${key} = ${JSON.stringify(value)};`);
  if (value) count++;
}

lines.push("");
lines.push("// Helper to get all injected env vars as a record");
lines.push("export const injectedEnv: Record<string, string> = {");
for (const key of ENV_KEYS) {
  lines.push(`  ${key},`);
}
lines.push("};");
lines.push("");

fs.writeFileSync(outputPath, lines.join("\n"));
console.log(`inject-env: wrote ${count}/${ENV_KEYS.length} env vars to ${outputPath}`);
