/**
 * Prebuild: writes env vars to src/lib/env-values.ts (auto-generated constants)
 * and env-injected.json (runtime fallback).
 */
const fs = require("fs");
const path = require("path");

const ENV_KEYS = [
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GOOGLE_REDIRECT_URI",
  "OAUTH_ENCRYPTION_KEY",
  "CRON_SECRET",
  "BLOG_API_KEY",
];

const envMap = {};
let count = 0;
for (const key of ENV_KEYS) {
  envMap[key] = process.env[key] || "";
  if (envMap[key]) count++;
}

// Write TS constants file
const tsPath = path.join(__dirname, "..", "src", "lib", "env-values.ts");
const tsLines = [
  "// AUTO-GENERATED by scripts/inject-env.js — DO NOT EDIT",
  "/* eslint-disable */",
  "",
];
for (const key of ENV_KEYS) {
  tsLines.push(`export const ${key} = ${JSON.stringify(envMap[key])};`);
}
tsLines.push("");
fs.writeFileSync(tsPath, tsLines.join("\n"));

// Write JSON fallback
const jsonPath = path.join(__dirname, "..", "env-injected.json");
fs.writeFileSync(jsonPath, JSON.stringify(envMap, null, 2));

console.log(`inject-env: wrote ${count}/${ENV_KEYS.length} env vars`);
// Debug: show value lengths to confirm they're non-empty
for (const key of ENV_KEYS) {
  console.log(`  ${key}: ${(envMap[key] || "").length} chars`);
}
// Verify written file
const written = require("fs").readFileSync(tsPath, "utf8");
console.log(`inject-env: env-values.ts is ${written.length} bytes, contains ${(written.match(/= "[^"]+"/g) || []).length} non-empty values`);
