/**
 * Prebuild script: writes env vars to TWO locations:
 * 1. src/lib/env-runtime.ts — compiled into bundle by Next.js
 * 2. .env-injected.json — read at runtime via fs (fallback)
 *
 * Workaround for Vercel bug where env vars added after initial project setup
 * are available during build but NOT injected into serverless function runtime.
 */
const fs = require("fs");
const path = require("path");

const ENV_KEYS = [
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "GOOGLE_REDIRECT_URI",
  "OAUTH_ENCRYPTION_KEY",
  "CRON_SECRET",
  "BLOG_API_KEY",
];

// Collect values
const envMap = {};
let count = 0;
for (const key of ENV_KEYS) {
  const value = process.env[key] || "";
  envMap[key] = value;
  if (value) count++;
}

// 1. Write TypeScript module
const tsPath = path.join(__dirname, "..", "src", "lib", "env-runtime.ts");
const tsLines = [
  "// AUTO-GENERATED by scripts/inject-env.js — DO NOT EDIT",
  "/* eslint-disable */",
  "",
];
for (const key of ENV_KEYS) {
  tsLines.push(`export const ${key} = ${JSON.stringify(envMap[key])};`);
}
tsLines.push("");
fs.writeFileSync(tsPath, tsLines.join("\n"));

// 2. Write JSON file at project root (for runtime fs.readFileSync fallback)
const jsonPath = path.join(__dirname, "..", "env-injected.json");
fs.writeFileSync(jsonPath, JSON.stringify(envMap, null, 2));

console.log(`inject-env: wrote ${count}/${ENV_KEYS.length} env vars`);
console.log(`  -> ${tsPath}`);
console.log(`  -> ${jsonPath}`);

// 3. Verify the TS file was actually written with values
const written = fs.readFileSync(tsPath, "utf8");
const hasValues = written.includes(envMap.GOOGLE_CLIENT_ID);
console.log(`  -> TS file verification: ${hasValues ? "OK - values present" : "FAIL - values missing"}`);
